yaml
name: Mirror to Gitee

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Mirror to Gitee
        env:
          GITEE_USERNAME: ${{ secrets.GITEE_USERNAME }}
          GITEE_TOKEN: ${{ secrets.GITEE_TOKEN }}
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git remote add gitee https://${{ secrets.GITEE_USERNAME }}:${{ secrets.GITEE_TOKEN }}@gitee.com/kasori4869/image-bed.git
          git push gitee --all --force
          git push gitee --tags --force

